# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alert-manager-0-2:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - /opt/bitnami/prometheus/conf/rules.yaml 
   - /opt/bitnami/prometheus/conf/alerts.yaml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  
  - job_name: 'graylog'
    scrape_interval: 15s
    metrics_path: '/api/plugins/org.graylog.plugins.metrics.prometheus/metrics'
    basic_auth:
      username: admin
      password: 4FTZOx9ACdbAw65WJH1u
    static_configs:
      - targets: ['appz.1276c99e.lowtouch.cloud:443/logs.alpha-dev/']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['172.31.12.178:9100', '172.31.64.16:9100', '172.31.64.14:9100']
    metric_relabel_configs:
      - source_labels: ['nodename']
        regex: 'loki-master'
        target_label: nodename
        replacement: loki-master
      - source_labels: ['nodename']
        regex: 'loki-worker-node-1'
        target_label: nodename
        replacement: loki-worker-node-1
      - source_labels: ['nodename']
        regex: 'loki-worker-node-0'
        target_label: nodename
        replacement: loki-worker-node-0

  - job_name: 'kube-state-metrics'
    static_configs:
    - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
